### PR TITLE
fixes #1

### LINKED ISSUE #1: triggering preview blanks vim until zathura is closed
as titled

### PR DESCRIPTION
**Pull request by FunctionalHacker**
Signed-off-by: Marko Korhonen <marko.korhonen@reekynet.com>

### CODE REVIEW

**Comment by FunctionalHacker** [comment]
Hold up, I should have probably tested this before submitting the PR

EDIT: Fixed now

**Comment by lingnand** [comment]
The indentation looks a bit weird - were you using tabs?

**Comment by FunctionalHacker** [comment]
How about now? I just made it one line as it is not too long

**Comment by lingnand** [comment]
My issue is more with the indentation of that line though - I would expect the `call` line to sit aligned with `let`, but github diff is apparently not so. Does this make sense?

**Comment by FunctionalHacker** [comment]
Sorry I was a bit busy last week. It appears that I accidentally used tabs instead of spaces on that line. Looked fine in my editor but it obviously was not right. Thanks for pointing it out

**Comment by lingnand** [comment]
No problem - thanks for the contribution!

**Pull request merged**
